export const UNTITLED = 'Untitled Session';

export function stripXml(text: string): string {
  return text.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
}

/** Placeholder titles some tools auto-generate when the user never named a session. */
const PLACEHOLDER_TITLE =
  /^(untitled|new session|new chat|untitled (codex|opencode|claude) session)\b/i;

export function isSystemCommand(text: string): boolean {
  const t = text.trim();
  if (!t) return false;
  // Raw XML wrappers: <command-name>, <local-command-caveat>, <system-reminder>, ...
  if (/^<\w+/.test(t)) return true;
  // Slash commands — "/clear", "/model claude-opus-5". A path like /home/x is not one.
  if (/^\/[a-zA-Z][\w-]*(\s|$)/.test(t)) return true;
  // Boilerplate Claude Code injects around local commands and resumed sessions.
  if (/^Caveat: The messages below were generated by the user/i.test(t)) return true;
  if (/^This session is being continued from a previous/i.test(t)) return true;
  return false;
}

/** True when a title carries no information about what the session was about. */
export function isPlaceholderTitle(title: string | undefined): boolean {
  const t = (title ?? '').trim();
  return !t || PLACEHOLDER_TITLE.test(t) || isSystemCommand(t);
}

/**
 * Pull readable text out of a message body, which may be a plain string or an
 * array of content blocks. Only text-bearing blocks contribute — tool calls and
 * tool results would otherwise leak raw JSON into titles.
 */
export function extractText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  const out: string[] = [];
  for (const block of content) {
    if (typeof block === 'string') {
      out.push(block);
      continue;
    }
    if (block && typeof block === 'object') {
      const b = block as Record<string, unknown>;
      if (b.type === 'text' && typeof b.text === 'string') out.push(b.text);
      else if (typeof b.text === 'string' && b.type === undefined) out.push(b.text);
    }
  }
  return out.join(' ').trim();
}

export function cleanTitle(raw: string, maxLen = 80): string {
  const cleaned = stripXml(raw);
  if (!cleaned || isSystemCommand(cleaned)) return UNTITLED;
  return cleaned.length > maxLen ? cleaned.slice(0, maxLen) + '…' : cleaned;
}

/** "2026-08-29 14:32" in local time — date plus the minute of the update. */
export function formatSessionTime(ts: number | undefined): string {
  if (!ts || !Number.isFinite(ts)) return 'unknown time';
  const d = new Date(ts);
  if (Number.isNaN(d.getTime())) return 'unknown time';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

export interface TitleSource {
  title?: string;
  lastMessage?: string;
  updatedAt?: number;
  createdAt?: number;
}

/**
 * Label for a session in a list: its own title when it has a real one, else a
 * snippet of the last message, else the date and minute it was last updated.
 */
export function displayTitle(session: TitleSource, maxLen = 80): string {
  const title = (session.title ?? '').trim();
  if (!isPlaceholderTitle(title)) {
    return title.length > maxLen ? title.slice(0, maxLen) + '…' : title;
  }

  const fromLast = cleanTitle(session.lastMessage ?? '', maxLen);
  if (fromLast !== UNTITLED) return fromLast;

  return `Untitled · ${formatSessionTime(session.updatedAt ?? session.createdAt)}`;
}
